"""
Library Management System
--------------------------
A simple in-memory library management system that supports:
  - Adding books (with multiple copies)
  - Registering members
  - Borrowing and returning books, with automatic late-fine calculation
  - Paying off member fines
  - Searching the catalogue by title or author
  - Listing members who currently have overdue books
  - Exporting the current library state to a JSON file

This file was originally submitted without comments or docstrings.
The comments and docstrings below were generated by an AI assistant
to document the existing logic, without changing behavior.
"""

import datetime
import json


class Book:
    """Represents a single title in the library catalogue.

    Tracks how many total copies the library owns and how many
    of those copies are currently available to be borrowed.
    """

    def __init__(self, isbn, title, author, copies=1):
        # Unique identifier for the book (International Standard Book Number)
        self.isbn = isbn
        self.title = title
        self.author = author
        # Total number of physical copies the library owns
        self.total_copies = copies
        # Copies not currently checked out by a member
        self.available_copies = copies

    def to_dict(self):
        """Return a plain-dict representation of this book, suitable for JSON export."""
        return {
            "isbn": self.isbn,
            "title": self.title,
            "author": self.author,
            "total_copies": self.total_copies,
            "available_copies": self.available_copies
        }


class Member:
    """Represents a registered library member.

    Keeps track of which books the member currently has on loan
    (mapped to their due dates) and any outstanding fines owed.
    """

    def __init__(self, member_id, name, email):
        self.member_id = member_id
        self.name = name
        self.email = email
        # Maps ISBN -> due date (datetime.date) for each book currently borrowed
        self.borrowed_books = {}
        # Running total of unpaid late fines, in currency units
        self.fines = 0.0

    def to_dict(self):
        """Return a plain-dict representation of this member, suitable for JSON export.

        Due dates are converted to ISO-format strings since datetime.date
        objects are not directly JSON-serializable.
        """
        return {
            "member_id": self.member_id,
            "name": self.name,
            "email": self.email,
            "borrowed_books": {
                isbn: due.isoformat() for isbn, due in self.borrowed_books.items()
            },
            "fines": self.fines
        }


class Library:
    """Central class that owns the book catalogue and member registry,
    and implements all borrowing/returning/fine business logic.
    """

    # Fine charged per day a book is returned late (currency units per day)
    FINE_PER_DAY = 0.5
    # Standard loan period given to a member when they borrow a book
    LOAN_PERIOD_DAYS = 14

    def __init__(self):
        # isbn -> Book
        self.books = {}
        # member_id -> Member
        self.members = {}

    def add_book(self, isbn, title, author, copies=1):
        """Add a new book to the catalogue, or increase the copy count
        if a book with the same ISBN already exists.
        """
        if isbn in self.books:
            # Book already known: just add more copies to existing stock
            self.books[isbn].total_copies += copies
            self.books[isbn].available_copies += copies
        else:
            self.books[isbn] = Book(isbn, title, author, copies)
        return self.books[isbn]

    def register_member(self, member_id, name, email):
        """Register a new library member. Raises if the member_id is already taken."""
        if member_id in self.members:
            raise ValueError("Member already exists")
        member = Member(member_id, name, email)
        self.members[member_id] = member
        return member

    def borrow_book(self, member_id, isbn):
        """Let a member borrow a copy of a book, subject to several checks:
          - the member and book must exist
          - a copy must currently be available
          - the member must not already be borrowing this same book
          - the member's outstanding fines must not exceed the allowed limit (5.0)

        Returns the calculated due date on success.
        """
        if member_id not in self.members:
            raise ValueError("Unknown member")
        if isbn not in self.books:
            raise ValueError("Unknown book")

        member = self.members[member_id]
        book = self.books[isbn]

        if book.available_copies <= 0:
            raise RuntimeError("No copies available")
        if isbn in member.borrowed_books:
            raise RuntimeError("Member already has this book")
        if member.fines > 5:
            # Members with too high an unpaid balance are blocked from borrowing more
            raise RuntimeError("Outstanding fines too high to borrow")

        due_date = datetime.date.today() + datetime.timedelta(days=self.LOAN_PERIOD_DAYS)
        member.borrowed_books[isbn] = due_date
        book.available_copies -= 1
        return due_date

    def return_book(self, member_id, isbn, return_date=None):
        """Process the return of a borrowed book.

        If returned after its due date, a late fine is calculated
        (LOAN days late * FINE_PER_DAY) and added to the member's balance.
        Defaults to today's date if no return_date is supplied
        (useful for testing with a specific date).

        Returns the fine amount charged for this particular return (0.0 if on time).
        """
        if member_id not in self.members:
            raise ValueError("Unknown member")
        member = self.members[member_id]

        if isbn not in member.borrowed_books:
            raise RuntimeError("Member did not borrow this book")

        if return_date is None:
            return_date = datetime.date.today()

        due_date = member.borrowed_books.pop(isbn)
        book = self.books[isbn]
        book.available_copies += 1

        late_days = (return_date - due_date).days
        fine = 0.0
        if late_days > 0:
            # Book was returned after the due date: calculate and apply fine
            fine = late_days * self.FINE_PER_DAY
            member.fines += fine

        return fine

    def pay_fine(self, member_id, amount):
        """Reduce a member's outstanding fine balance by the given amount.

        The balance is floored at 0.0 (overpayment is not tracked as credit).
        Returns the member's remaining fine balance after payment.
        """
        if member_id not in self.members:
            raise ValueError("Unknown member")
        member = self.members[member_id]
        if amount <= 0:
            raise ValueError("Payment must be positive")
        member.fines = max(0.0, member.fines - amount)
        return member.fines

    def search_by_title(self, keyword):
        """Case-insensitive substring search over book titles."""
        keyword = keyword.lower()
        return [b for b in self.books.values() if keyword in b.title.lower()]

    def search_by_author(self, keyword):
        """Case-insensitive substring search over book authors."""
        keyword = keyword.lower()
        return [b for b in self.books.values() if keyword in b.author.lower()]

    def overdue_members(self):
        """Return a list of (member_id, isbn, days_overdue) tuples for every
        currently-borrowed book that is past its due date.
        """
        today = datetime.date.today()
        overdue = []
        for member in self.members.values():
            for isbn, due in member.borrowed_books.items():
                if due < today:
                    overdue.append((member.member_id, isbn, (today - due).days))
        return overdue

    def export_state(self, filepath):
        """Write the current catalogue and membership data to a JSON file
        at the given filepath, for backup or inspection purposes.
        """
        state = {
            "books": [b.to_dict() for b in self.books.values()],
            "members": [m.to_dict() for m in self.members.values()]
        }
        with open(filepath, "w") as f:
            json.dump(state, f, indent=2)


def demo():
    """Small end-to-end demonstration of the library workflow:
    add books, register members, borrow, return late (to show fine
    calculation), search the catalogue, and export the final state.
    """
    lib = Library()
    lib.add_book("111", "Clean Code", "Robert C. Martin", 2)
    lib.add_book("222", "The Pragmatic Programmer", "Andrew Hunt", 1)
    lib.register_member("M1", "Ada Lovelace", "ada@example.com")
    lib.register_member("M2", "Alan Turing", "alan@example.com")

    due = lib.borrow_book("M1", "111")
    print("M1 borrowed 111, due", due)

    # Return 3 days after the due date to demonstrate fine calculation
    fine = lib.return_book("M1", "111", return_date=due + datetime.timedelta(days=3))
    print("Late fine charged:", fine)

    results = lib.search_by_title("clean")
    print("Search results:", [b.title for b in results])

    lib.export_state("library_state.json")


if __name__ == "__main__":
    demo()
